### ISSUE TITLE
Online demo becomes unresponsive after a while;

### ISSUE THREAD

**Issue by BenHayat** [DevExpress/RazorComponents#6]
Hello Team;
As I was testing the online demo, I notice If I don't interact with it for a while, and then try to use the dropdown box or date component, it becomes unresponsive.
Is this a problem with Razor Component and SignalR or related to your components?

Thanks!
..Ben

**Comment by Mehul** [comment]
@BenHayat 1. What browser?
2. How long before it stopped responding please?

Thanks.

**Comment by BenHayat** [comment]
FF.
I have not measured the time yet, but if you test it in FF and leave it alone for 15 minutes, you should see it. I first wanted to see if it is Razor problem or yours.

**Comment by BenHayat** [comment]
Hi Mehul;
I went ahead and did several time tests (5 min, 10 min, 35 min) and so far working.
I'll keep an eye on it to see what else could affect it.

**Comment by SergeySeleznyov** [comment]
Hello @BenHayat,

It depends on environment.
From my experience:
 - Connection to IIS express can be lost.
 - When I published my test sample to MS Azure, the connection was working for a week (I deliberately tested how long it could live); maybe the connection could have existed even longer, but I accidentally closed the browser.
 - Connection to our demo server may be lost due to many reasons, for instance, due to some updates.
 - After the connection is lost, Razor Components do not try to reconnect. Hope MS will overcome it soon.
So, I would recommend publishing your project to some reliable place (like MS Azure).

About DropDown based components. All the components are native Blazor/RazorComponents.
Even the DropDown window is shown on the server side to provide server-side templates.
So, if connection was lost and wasn't restored, you can't close them.

I think we can try to detect that the connection was lost and report it to the user to provide better experience until MS fixes it.

**Comment by SergeySeleznyov** [comment]
Microsoft is working on it:
https://youtu.be/ap60h3eQE5Y?t=4042

**Comment by SergeySeleznyov** [comment]
Hi @BenHayat ,

Our webinar about the Blazor is going to start soon:
https://www.devexpress.com/support/webinars/
Would be great to see you there.

**Comment by BenHayat** [comment]
Hi Sergey;
As I had mentioned to Mehul, I have an important call coming in at the exact time, unfortunately.
